version: '3.3'

services:
  ttsapi:
    build: .
    container_name: ttsapi
    network_mode: bridge
    volumes:
      - /var/run/mysqld/mysqld.sock:/root/mysqld.sock:rw
    ports:
      - "5000:5000"
    restart: unless-stopped
